### ISSUE TITLE
attrdict dependence breaks markdown_note in python 3.10

### ISSUE THREAD

**Issue by DrSAR** [KnorrFG/markdown_note#1]
When installing under python 3.10 the dependency attrdict results in errors in four files:
```
~/miniconda3/envs/MarkdownNotes/lib/python3.10/site-packages/attrdict/mapping.py
~/miniconda3/envs/MarkdownNotes/lib/python3.10/site-packages/attrdict/mixins.py
~/miniconda3/envs/MarkdownNotes/lib/python3.10/site-packages/attrdict/merge.py
~/miniconda3/envs/MarkdownNotes/lib/python3.10/site-packages/attrdict/default.py
```
In all cases this can be fixed by changing
``` python
from collections.abc import Mapping
```
to 
``` python
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping
```

However, I believe `attrdict` has been abandoned and I wonder if it's possible/prudent to remove the use of `AttrDict` in core.py.

**Comment by KnorrFG** [comment]
Hey, thanks for the report. I  removed AttrDict, and provided a simple custom implementation that should suffice for the current uses.
